bill_price = float(input("შეიყვანეთ ჩეკის თანხა: "))
tips_percentage = int(input("შეიყვანეთ ჩაის პროცენტული რაოდენობა: "))
guests_amount = int(input("შეიყვანეთ სტუმართა რაოდენობა: "))
tips_amount = (round(bill_price * tips_percentage / 100, 2))
bill_total = (round(bill_price + tips_amount, 2))
bill_per_person = (round(bill_total / guests_amount, 2))
print("ჩაის ფული იქნება", tips_amount, "ლარი")
print("ჩეკის მთლიანი საფასური იქნება", bill_total, "ლარი")
print("თითოეული სტუმრის გადასახდელი თანხა იქნება", bill_per_person, "ლარი")